//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_servis_ile_veri_çekme.ServiceAltinKaynak {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://data.altinkaynak.com/", ConfigurationName="ServiceAltinKaynak.DataServiceSoap")]
    public interface DataServiceSoap {
        
        // CODEGEN: Generating message contract since message GetCurrencyRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetCurrency", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        web_servis_ile_veri_çekme.ServiceAltinKaynak.GetCurrencyResponse GetCurrency(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetCurrency", ReplyAction="*")]
        System.Threading.Tasks.Task<web_servis_ile_veri_çekme.ServiceAltinKaynak.GetCurrencyResponse> GetCurrencyAsync(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetCurrencyRequest request);
        
        // CODEGEN: Generating message contract since message GetGoldRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetGold", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        web_servis_ile_veri_çekme.ServiceAltinKaynak.GetGoldResponse GetGold(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetGoldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetGold", ReplyAction="*")]
        System.Threading.Tasks.Task<web_servis_ile_veri_çekme.ServiceAltinKaynak.GetGoldResponse> GetGoldAsync(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetGoldRequest request);
        
        // CODEGEN: Generating message contract since message GetMainRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetMain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        web_servis_ile_veri_çekme.ServiceAltinKaynak.GetMainResponse GetMain(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetMainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetMain", ReplyAction="*")]
        System.Threading.Tasks.Task<web_servis_ile_veri_çekme.ServiceAltinKaynak.GetMainResponse> GetMainAsync(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetMainRequest request);
        
        // CODEGEN: Generating message contract since message GetParityRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetParity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        web_servis_ile_veri_çekme.ServiceAltinKaynak.GetParityResponse GetParity(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetParityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetParity", ReplyAction="*")]
        System.Threading.Tasks.Task<web_servis_ile_veri_çekme.ServiceAltinKaynak.GetParityResponse> GetParityAsync(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetParityRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.altinkaynak.com/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrency", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetCurrencyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://data.altinkaynak.com/")]
        public web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader;
        
        public GetCurrencyRequest() {
        }
        
        public GetCurrencyRequest(web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrencyResponse", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetCurrencyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://data.altinkaynak.com/", Order=0)]
        public string GetCurrencyResult;
        
        public GetCurrencyResponse() {
        }
        
        public GetCurrencyResponse(string GetCurrencyResult) {
            this.GetCurrencyResult = GetCurrencyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGold", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetGoldRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://data.altinkaynak.com/")]
        public web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader;
        
        public GetGoldRequest() {
        }
        
        public GetGoldRequest(web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGoldResponse", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetGoldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://data.altinkaynak.com/", Order=0)]
        public string GetGoldResult;
        
        public GetGoldResponse() {
        }
        
        public GetGoldResponse(string GetGoldResult) {
            this.GetGoldResult = GetGoldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMain", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetMainRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://data.altinkaynak.com/")]
        public web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader;
        
        public GetMainRequest() {
        }
        
        public GetMainRequest(web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMainResponse", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetMainResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://data.altinkaynak.com/", Order=0)]
        public string GetMainResult;
        
        public GetMainResponse() {
        }
        
        public GetMainResponse(string GetMainResult) {
            this.GetMainResult = GetMainResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParity", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetParityRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://data.altinkaynak.com/")]
        public web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader;
        
        public GetParityRequest() {
        }
        
        public GetParityRequest(web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParityResponse", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetParityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://data.altinkaynak.com/", Order=0)]
        public string GetParityResult;
        
        public GetParityResponse() {
        }
        
        public GetParityResponse(string GetParityResult) {
            this.GetParityResult = GetParityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceSoapChannel : web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceSoapClient : System.ServiceModel.ClientBase<web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap>, web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap {
        
        public DataServiceSoapClient() {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_servis_ile_veri_çekme.ServiceAltinKaynak.GetCurrencyResponse web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap.GetCurrency(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetCurrencyRequest request) {
            return base.Channel.GetCurrency(request);
        }
        
        public string GetCurrency(web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader) {
            web_servis_ile_veri_çekme.ServiceAltinKaynak.GetCurrencyRequest inValue = new web_servis_ile_veri_çekme.ServiceAltinKaynak.GetCurrencyRequest();
            inValue.AuthHeader = AuthHeader;
            web_servis_ile_veri_çekme.ServiceAltinKaynak.GetCurrencyResponse retVal = ((web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap)(this)).GetCurrency(inValue);
            return retVal.GetCurrencyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web_servis_ile_veri_çekme.ServiceAltinKaynak.GetCurrencyResponse> web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap.GetCurrencyAsync(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetCurrencyRequest request) {
            return base.Channel.GetCurrencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<web_servis_ile_veri_çekme.ServiceAltinKaynak.GetCurrencyResponse> GetCurrencyAsync(web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader) {
            web_servis_ile_veri_çekme.ServiceAltinKaynak.GetCurrencyRequest inValue = new web_servis_ile_veri_çekme.ServiceAltinKaynak.GetCurrencyRequest();
            inValue.AuthHeader = AuthHeader;
            return ((web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap)(this)).GetCurrencyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_servis_ile_veri_çekme.ServiceAltinKaynak.GetGoldResponse web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap.GetGold(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetGoldRequest request) {
            return base.Channel.GetGold(request);
        }
        
        public string GetGold(web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader) {
            web_servis_ile_veri_çekme.ServiceAltinKaynak.GetGoldRequest inValue = new web_servis_ile_veri_çekme.ServiceAltinKaynak.GetGoldRequest();
            inValue.AuthHeader = AuthHeader;
            web_servis_ile_veri_çekme.ServiceAltinKaynak.GetGoldResponse retVal = ((web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap)(this)).GetGold(inValue);
            return retVal.GetGoldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web_servis_ile_veri_çekme.ServiceAltinKaynak.GetGoldResponse> web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap.GetGoldAsync(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetGoldRequest request) {
            return base.Channel.GetGoldAsync(request);
        }
        
        public System.Threading.Tasks.Task<web_servis_ile_veri_çekme.ServiceAltinKaynak.GetGoldResponse> GetGoldAsync(web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader) {
            web_servis_ile_veri_çekme.ServiceAltinKaynak.GetGoldRequest inValue = new web_servis_ile_veri_çekme.ServiceAltinKaynak.GetGoldRequest();
            inValue.AuthHeader = AuthHeader;
            return ((web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap)(this)).GetGoldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_servis_ile_veri_çekme.ServiceAltinKaynak.GetMainResponse web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap.GetMain(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetMainRequest request) {
            return base.Channel.GetMain(request);
        }
        
        public string GetMain(web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader) {
            web_servis_ile_veri_çekme.ServiceAltinKaynak.GetMainRequest inValue = new web_servis_ile_veri_çekme.ServiceAltinKaynak.GetMainRequest();
            inValue.AuthHeader = AuthHeader;
            web_servis_ile_veri_çekme.ServiceAltinKaynak.GetMainResponse retVal = ((web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap)(this)).GetMain(inValue);
            return retVal.GetMainResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web_servis_ile_veri_çekme.ServiceAltinKaynak.GetMainResponse> web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap.GetMainAsync(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetMainRequest request) {
            return base.Channel.GetMainAsync(request);
        }
        
        public System.Threading.Tasks.Task<web_servis_ile_veri_çekme.ServiceAltinKaynak.GetMainResponse> GetMainAsync(web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader) {
            web_servis_ile_veri_çekme.ServiceAltinKaynak.GetMainRequest inValue = new web_servis_ile_veri_çekme.ServiceAltinKaynak.GetMainRequest();
            inValue.AuthHeader = AuthHeader;
            return ((web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap)(this)).GetMainAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_servis_ile_veri_çekme.ServiceAltinKaynak.GetParityResponse web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap.GetParity(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetParityRequest request) {
            return base.Channel.GetParity(request);
        }
        
        public string GetParity(web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader) {
            web_servis_ile_veri_çekme.ServiceAltinKaynak.GetParityRequest inValue = new web_servis_ile_veri_çekme.ServiceAltinKaynak.GetParityRequest();
            inValue.AuthHeader = AuthHeader;
            web_servis_ile_veri_çekme.ServiceAltinKaynak.GetParityResponse retVal = ((web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap)(this)).GetParity(inValue);
            return retVal.GetParityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web_servis_ile_veri_çekme.ServiceAltinKaynak.GetParityResponse> web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap.GetParityAsync(web_servis_ile_veri_çekme.ServiceAltinKaynak.GetParityRequest request) {
            return base.Channel.GetParityAsync(request);
        }
        
        public System.Threading.Tasks.Task<web_servis_ile_veri_çekme.ServiceAltinKaynak.GetParityResponse> GetParityAsync(web_servis_ile_veri_çekme.ServiceAltinKaynak.AuthHeader AuthHeader) {
            web_servis_ile_veri_çekme.ServiceAltinKaynak.GetParityRequest inValue = new web_servis_ile_veri_çekme.ServiceAltinKaynak.GetParityRequest();
            inValue.AuthHeader = AuthHeader;
            return ((web_servis_ile_veri_çekme.ServiceAltinKaynak.DataServiceSoap)(this)).GetParityAsync(inValue);
        }
    }
}
